package com.example.cmput301;

import java.util.List;

public class TaskManager {

    private List<Task> tasks;

    /**
     * Attaches task to the local database and returns the task which was added
     * along with it's id.
     *
     * @param task The task you want to be added.
     * @return The task which was added with the local task id attached.
     */
    public Task addTask(Task task) {

        Task addedTask = DatabaseManager.postLocal(task);

        return addedTask;
    }

    /**
     * Share the task with the given id.
     *
     * @param id The id of the task you want shared.
     */
    public void shareTask(String id) {

        //Get the task from the database.
        Task localTask = DatabaseManager.getLocalTask(id);

        //Post to the webservice.
        Task remoteTask = WebService.post(localTask);

        //--
        //Since we are replacing the id we need to remove the old task and put in
        //a new one with an id generated by the webservice.
        //--

        //Remove the local version of the task.
        DatabaseManager.deleteLocalTask(localTask.getId());

        //Add the remote version of the task.
        remoteTask.setStatus(Task.STATUS_SHARED);
        DatabaseManager.postLocal(remoteTask);

    }

    public boolean deleteTask(String id) {

        WebService.deleteTask(id);

        return true;
    }
    
     /**
     * Post a response to a task with the given id in the database.
     *
     * @param response
     * @param task
     */
    public void postResponse(Task task, Response response) {
        
        //If its private dont update the webservice first.
        if(task.getStatus() == Task.STATUS_PRIVATE) {
            task.addResponse(response);
            DatabaseManager.updateTask(task);
        } else {
            Task updatedTask = WebService.postResponse(task, response);
            DatabaseManager.updateTask(updatedTask);
        }
    }

    
}
